### ISSUE TITLE
Bottom copyright panel persists in front of data table

### ISSUE THREAD

**Issue by DavidOry** [MetropolitanTransportationCommission/ClimateActionPortal#34]
After selecting the TAZs and displaying the data, the bottom Copyright ribbon persists in front of the data table.  It then blocks the view of the data table. 

<img width="1280" alt="screen shot 2016-02-09 at 2 11 42 pm" src="https://cloud.githubusercontent.com/assets/6684315/12932432/a02ea0ca-cf37-11e5-8f3b-f08be5d3b045.png">

**Comment by tombuckley** [comment]
This issue was moved to MetropolitanTransportationCommission/CAPVMT#20
