### ISSUE TITLE
Check calculations

### ISSUE THREAD

**Issue by DavidOry** [MetropolitanTransportationCommission/ClimateActionPortal#37]
It *appears* the sums are off for the forecast years.  I'll track down what the numbers should be and share them here.

**Comment by DavidOry** [comment]
My estimates and the current estimates in the tool (in parentheses) are:

2010: 109,797,472 (109,797,472)
2020: 115,538,796 (231,077,593)
2030: 120,217,415 (240,434,829)
2040: 126,117,627 (252,235,255)

The 2020, 2030, and 2040 numbers are exactly 2 times what they should be.

**Comment by Keareys** [comment]
I have passed this one on to Lisa.  I checked the front end and summary views.  All seems appropriate.  Lisa will check the sql script to confirm any errors with the underlying data table processing.

**Comment by lmz** [comment]
Ooops, I think this is due to a bug in the core summaries script (an extraneous SAMPLESHARE divide).  Sorry about that!  I'll update the vmt tables in the database and let @Keareys know when it's done so he can regenerate the cached table(s?).
