### ISSUE TITLE
Public Comment: Add a lookup table for each simulation year with EMFAC county level data on fuel type mix, commercial vehicle activity, and CO2 output.  Perhaps with instructions on how to allocate to your city.

### ISSUE THREAD

**Issue by MTCGIS** [MetropolitanTransportationCommission/ClimateActionPortal#42]
Add a lookup table for each simulation year with EMFAC county level data on fuel type mix, commercial vehicle activity, and CO2 output.  Perhaps with instructions on how to allocate to your city.

**Comment by tombuckley** [comment]
This issue was moved to MetropolitanTransportationCommission/CAPVMT#15
