### ISSUE TITLE
Map Tools: Create TAZ Inspection Tool

### ISSUE THREAD

**Issue by Keareys** [MetropolitanTransportationCommission/ClimateActionPortal#5]
Add Popup note for TAZs that report back the following data:
Base Year Population: (2005)
Projected Population: (2040)
Base Year Employment: (2005)
Projected Employment: (2040)

This can be a chart tool as well.

**Comment by tombuckley** [comment]
moved to https://github.com/MetropolitanTransportationCommission/CAPVMT/issues/25
