### ISSUE TITLE
Map Tools: Select Custom Zones

### ISSUE THREAD

**Issue by Keareys** [MetropolitanTransportationCommission/ClimateActionPortal#6]
Build Selection Tool that allows user to select custom zones from the map based upon user map click on features.  One Click selects feature, Second Click on same feature deselects feature. (Nadia will work on Map Feature portion of this.)

Tool should allow user to see a list of the selected TAZs as user makes them. (Kearey will work on UI portion of this)

**Comment by tombuckley** [comment]
moved here: https://github.com/MetropolitanTransportationCommission/CAPVMT/issues/24
